sudo: required

dist: trusty

language: cpp

compiler:
  - g++
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
notifications:
  email: false
sudo: false

script:
  - make clean
  - make -j2
  - make test

